<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Version>1.1.0</Version>
    <AssemblyName>System Squire</AssemblyName>
    <ApplicationIcon>Assets\system-squire-icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Win32Resource />
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\system-squire-icon.png" />
    <Resource Include="Assets\system-squire-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Tools\minimize-to-tray.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
      <TargetPath>Tools\minimize-to-tray.exe</TargetPath>
    </None>
  </ItemGroup>
</Project>
